# Generated by Django 4.1.1 on 2023-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=32)),
                ('hotelstars', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=32)),
                ('outbounddeparturedatetime', models.DateTimeField()),
                ('inbounddeparturedatetime', models.DateTimeField()),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=3)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=32)),
                ('inbounddepartureairport', models.CharField(max_length=3)),
                ('inboundarrivalairport', models.CharField(max_length=3)),
                ('inboundarrivaldatetime', models.DateTimeField()),
                ('outbounddepartureairport', models.CharField(max_length=3)),
                ('outboundarrivalairport', models.CharField(max_length=3)),
                ('outboundarrivaldatetime', models.DateTimeField()),
                ('mealtype', models.CharField(max_length=32)),
                ('oceanview', models.BooleanField()),
                ('roomtype', models.CharField(max_length=32)),
            ],
        ),
    ]
