# Generated by Django 4.1.1 on 2023-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=32)),
                ('depaturedate', models.DateTimeField()),
                ('returndate', models.DateTimeField()),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=3)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=32)),
                ('inbounddepartureairport', models.CharField(max_length=3)),
                ('inboundarrivalairport', models.CharField(max_length=3)),
                ('inboundairline', models.CharField(max_length=3)),
                ('inboundarrivaldatetime', models.DateTimeField()),
                ('outbounddepartureairport', models.CharField(max_length=3)),
                ('outboundarrivalairport', models.CharField(max_length=3)),
                ('outboundairline', models.CharField(max_length=3)),
                ('outboundarrivaldatetime', models.DateTimeField()),
                ('mealtype', models.CharField(max_length=32)),
                ('oceanview', models.BooleanField()),
                ('roomtype', models.CharField(max_length=32)),
            ],
        ),
    ]
