# Generated by Django 4.1.1 on 2023-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='first',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('mealtype', models.DecimalField(decimal_places=0, max_digits=1)),
                ('oceanview', models.BooleanField()),
                ('roomtype', models.DecimalField(decimal_places=0, max_digits=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='offerAMS',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBER',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBLL',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBRE',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBRN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBRU',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerBSL',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerCGN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerCRL',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerCSO',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerDRS',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerDTM',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerDUS',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerEIN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerERF',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerFDH',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerFKB',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerFMM',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerFMO',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerFRA',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerGRZ',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerGVA',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerGWT',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerHAJ',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerHAM',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerHHH',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerINN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerKLU',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerKRK',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerKSF',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerLBC',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerLEJ',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerLNZ',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerLUX',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerMUC',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerNRN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerNUE',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerPAD',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerPRG',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerRLG',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerRTM',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerSCN',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerSTR',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerSXB',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerSZG',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerVIE',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerWAW',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='offerZRH',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('countadults', models.DecimalField(decimal_places=0, max_digits=2)),
                ('countchildren', models.DecimalField(decimal_places=0, max_digits=2)),
                ('startdate', models.DateField()),
                ('days', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hotelid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='second',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('mealtype', models.DecimalField(decimal_places=0, max_digits=1)),
                ('oceanview', models.BooleanField()),
                ('roomtype', models.DecimalField(decimal_places=0, max_digits=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('outbounddeparturedatetime', models.DateTimeField()),
                ('inbounddeparturedatetime', models.DateTimeField()),
                ('outboundarrivaldatetime', models.DateTimeField()),
                ('inboundarrivaldatetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
