# Generated by Django 4.1.1 on 2023-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_first_offerams_offerber_offerbll_offerbre_offerbrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='roomtype',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='second',
            name='roomtype',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
